/**
 * @fileoverview gRPC-Web generated client stub for hello.v1alpha1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v0.0.0
// source: hello/v1alpha1/hello.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.hello = {};
proto.hello.v1alpha1 = require('./hello_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hello.v1alpha1.HelloServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hello.v1alpha1.HelloServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hello.v1alpha1.SayHelloRequest,
 *   !proto.hello.v1alpha1.SayHelloResponse>}
 */
const methodDescriptor_HelloService_SayHello = new grpc.web.MethodDescriptor(
  '/hello.v1alpha1.HelloService/SayHello',
  grpc.web.MethodType.UNARY,
  proto.hello.v1alpha1.SayHelloRequest,
  proto.hello.v1alpha1.SayHelloResponse,
  /**
   * @param {!proto.hello.v1alpha1.SayHelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hello.v1alpha1.SayHelloResponse.deserializeBinary
);


/**
 * @param {!proto.hello.v1alpha1.SayHelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hello.v1alpha1.SayHelloResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hello.v1alpha1.SayHelloResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hello.v1alpha1.HelloServiceClient.prototype.sayHello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hello.v1alpha1.HelloService/SayHello',
      request,
      metadata || {},
      methodDescriptor_HelloService_SayHello,
      callback);
};


/**
 * @param {!proto.hello.v1alpha1.SayHelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hello.v1alpha1.SayHelloResponse>}
 *     Promise that resolves to the response
 */
proto.hello.v1alpha1.HelloServicePromiseClient.prototype.sayHello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hello.v1alpha1.HelloService/SayHello',
      request,
      metadata || {},
      methodDescriptor_HelloService_SayHello);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hello.v1alpha1.SayGoodbyeRequest,
 *   !proto.hello.v1alpha1.SayGoodbyeResponse>}
 */
const methodDescriptor_HelloService_SayGoodbye = new grpc.web.MethodDescriptor(
  '/hello.v1alpha1.HelloService/SayGoodbye',
  grpc.web.MethodType.UNARY,
  proto.hello.v1alpha1.SayGoodbyeRequest,
  proto.hello.v1alpha1.SayGoodbyeResponse,
  /**
   * @param {!proto.hello.v1alpha1.SayGoodbyeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hello.v1alpha1.SayGoodbyeResponse.deserializeBinary
);


/**
 * @param {!proto.hello.v1alpha1.SayGoodbyeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hello.v1alpha1.SayGoodbyeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hello.v1alpha1.SayGoodbyeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hello.v1alpha1.HelloServiceClient.prototype.sayGoodbye =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hello.v1alpha1.HelloService/SayGoodbye',
      request,
      metadata || {},
      methodDescriptor_HelloService_SayGoodbye,
      callback);
};


/**
 * @param {!proto.hello.v1alpha1.SayGoodbyeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hello.v1alpha1.SayGoodbyeResponse>}
 *     Promise that resolves to the response
 */
proto.hello.v1alpha1.HelloServicePromiseClient.prototype.sayGoodbye =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hello.v1alpha1.HelloService/SayGoodbye',
      request,
      metadata || {},
      methodDescriptor_HelloService_SayGoodbye);
};


module.exports = proto.hello.v1alpha1;

